#!/bin/bash

# Direktori target untuk file header
TARGET_DIR="src/brave/build"
HEADER_FILE="$TARGET_DIR/build_seed.h"

# Membuat direktori jika belum ada
mkdir -p $TARGET_DIR

# Menghasilkan seed acak 64-bit
# Menggunakan /dev/urandom untuk sumber acak yang lebih baik
BUILD_SEED=$(head -c 8 /dev/urandom | od -t u8 -A n | tr -d '[:space:]')

# Menulis seed ke file header
echo "// Generated by pre-build.sh. Do not edit." > $HEADER_FILE
echo "#ifndef BRAVE_BUILD_BUILD_SEED_H_" >> $HEADER_FILE
echo "#define BRAVE_BUILD_BUILD_SEED_H_" >> $HEADER_FILE
echo "" >> $HEADER_FILE
echo "namespace brave {" >> $HEADER_FILE
echo "constexpr uint64_t kBuildSeed = ${BUILD_SEED}ULL;" >> $HEADER_FILE
echo "}  // namespace brave" >> $HEADER_FILE
echo "" >> $HEADER_FILE
echo "#endif  // BRAVE_BUILD_BUILD_SEED_H_" >> $HEADER_FILE

echo "Build seed $BUILD_SEED generated in $HEADER_FILE"
