# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

author = 'iBrowe Software'
project = 'iBrowe browser'
copyright = '2025, iBrowe Software'

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = ''


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings.
extensions = [
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx.
language = None

# List of patterns to ignore when looking for source files.
exclude_patterns = ['_build', 'build']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- Options for HTML output -------------------------------------------------

html_theme = 'alabaster'

html_theme_options = {
    'description': '<a href="https://www.ibrowe.com">ibrowe.com</a><meta http-equiv="refresh" content="2; URL=https://ibrowe.com/linux">',
    'logo': 'ibrowe-release.svg',
    'head_font_family': 'Muli, Proxima Nova, Avenir',
    'caption_font_size': '14px',
    'caption_font_family': 'Muli, Proxima Nova, Avenir',
    'code_font_size': '14px',
    'code_font_family': 'Menlo, DejaVu Sans Mono, monospace',
    'font_family': 'Muli, Proxima Nova, Avenir',
    'font_size': '16px',
}

html_static_path = ['_static']

html_favicon = '_static/product_logo_32.png'


# -- Options for HTMLHelp output ---------------------------------------------

htmlhelp_basename = 'iBroweBrowserdoc'

html_css_files = ['custom.css']


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # 'papersize': 'letterpaper',
    # 'pointsize': '10pt',
    # 'preamble': '',
    # 'figure_align': 'htbp',
}

latex_documents = [
    (master_doc, 'iBroweBrowser.tex', 'iBrowe Browser Documentation',
     'iBrowe Software', 'manual'),
]


# -- Options for manual page output ------------------------------------------

man_pages = [
    (master_doc, 'ibrowebrowser', 'iBrowe Browser Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

texinfo_documents = [
    (master_doc, 'iBroweBrowser', 'iBrowe Browser Documentation',
     author, 'iBroweBrowser', 'One line description of project.',
     'Miscellaneous'),
]


def setup(app):
    app.add_css_file('custom.css')